# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [30]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [31]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [32]:
#Your code starts here

filename = fnmatch.filter(os.listdir(), '*txt')
for files in filename:
    files_dict[files]=file_count
    file_count=file_count+1


#Your code ends here       

Displaying the count of files.

In [33]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 8


Displaying Dictionary containing all files.

In [34]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'file1.txt': 0, 'file2.txt': 1, 'file3.txt': 2, 'file4.txt': 3, 'file5.txt': 4, 'file6.txt': 5, 'file7.txt': 6, 'file8.txt': 7}


# Step 3 Extract Unique Vocabulary

In [ ]:
# write code to print all the unique words in every file and store them in a set

In [35]:
#Your code starts here    
for files in filename:
    text_file = open(files, 'r')
    text = text_file.read()

#cleaning
    text = text.lower()
    words = text.split()
    words = [word.strip('.,!;()[]') for word in words]
    words = [word.replace("'s", '') for word in words]

#finding unique
    unique = []
    for word in words:
        if word not in unique:
             unique_word_set.add(word)


#print
print(unique_word_set)
#Your code ends here

{'this', '6', 'file', '4', '5', '2', '3', 'is', '7', '1', '8'}


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [ ]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [36]:
var = np.zeros((len(filename) ,len(unique_word_set)))
print(var)

c = 0
word_dict = dict()

for ch in unique_word_set:
    if ch not in word_dict:
        word_dict[ch]=c
        c +=1
print(word_dict)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'this': 0, '6': 1, 'file': 2, '4': 3, '5': 4, '2': 5, '3': 6, 'is': 7, '7': 8, '1': 9, '8': 10}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [ ]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [37]:
for files in files_dict.keys():
    
    pro = open(files, "r")
    ptr = pro.read()
    
    for ch in unique_word_set:
        for val in ptr.split():
            if ch in val:
                var[files_dict[files]][word_dict[ch]] = 1
                
print(var)

[[0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [ ]:
# For user query make a column vector of length of all the unique words present in a set

In [38]:
prep = np.zeros((1, len(unique_word_set))).T

print(prep)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [39]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary



Write something for searching  1 2 3 4 5


In [40]:
for meta in query.split():
    if meta in unique_word_set:
        prep[word_dict[meta]][0] = prep[word_dict[meta]][0] + 1
print(prep)

[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [41]:
mint = np.matmul(var, prep)
mount= mint.max()
i = 0
for ind in range(0,len(mint)):
    if mint[i][0] == mount:
        i = ind
        break
print(mint)
print("Max value in the resultant vector are : ",mount)
print("Index of max value in resultant vector are : ",i)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]]
Max value in the resultant vector are :  1.0
Index of max value in resultant vector are :  0


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [ ]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [42]:
key_id = list(files_dict.keys())
key_value = list(files_dict.values())
 
curr = key_value[i]
data = key_id[curr]

heaven= open(data, "r")
string = heaven.read()
print("Contents are: ", string)

Contents are:  This is file 1.


Congratulations Now you are able to build your own small IRS.